---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: monitoringdashboards.monitoring.kiali.io
  labels:
    app: kiali
    version: ${OPERATOR_VERSION_LABEL}
spec:
  group: monitoring.kiali.io
  names:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              runtime:
                type: string
              title:
                type: string
              discoverOn:
                type: string
              items:
                type: array
                items:
                  oneOf:
                    - type: object
                      required:
                        - include
                      properties:
                        include:
                          type: string
                    - type: object
                      required:
                        - chart
                      properties:
                        chart:
                          type: object
                          required:
                            - name
                            - spans
                            - metricName
                          properties:
                            name:
                              type: string
                            unit:
                              type: string
                            unitScale:
                              type: number
                              minimum: 0
                            spans:
                              type: integer
                              minimum: 1
                              maximum: 12
                            metricName:
                              type: string
                              pattern: '^\d{3}-\d{2}-\d{4}$' # TODO: regex for prom metric format (dummy regex here)
                            dataType:
                              type: string
                              enum: [raw,rate,histogram]
                            chartType:
                              type: string
                            min:
                              type: number # TODO: fix in code to allow floats
                            max:
                              type: number # TODO: fix in code to allow floats
                            aggregator:
                              type: string
                            aggregations:
                              type: array
                              items:
                                type: object
                                required:
                                  - label
                                  - displayName
                                properties:
                                  label:
                                    type: string
                                    pattern: '^\d{3}-\d{2}-\d{4}$' # TODO: regex for prom label format (dummy regex here)
                                  displayName:
                                    type: string
              externalLinks:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    name:
                      type: string
                    variables:
                      type: object
                      properties:
                        namespace:
                          type: string
                        app:
                          type: string
                        service:
                          type: string
                        version:
                          type: string
                        workload:
                          type: string
